[package]
name = "rissue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4"
mime = "0.3"
sqlite = "0.33"
serde = {version = "1.0", features = ["derive"]}
